/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectId = IDL.Nat;
export const Time = IDL.Int;
export const TaskId = IDL.Nat;
export const Project = IDL.Record({
  'id' : ProjectId,
  'owner' : IDL.Principal,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'color' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Task = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'completionDate' : IDL.Opt(Time),
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'completed' : IDL.Bool,
  'dueDate' : Time,
  'description' : IDL.Opt(IDL.Text),
  'longFormContent' : IDL.Opt(IDL.Text),
  'projectId' : IDL.Opt(ProjectId),
  'priority' : IDL.Text,
});
export const TimePeriodStats = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completionRate' : IDL.Float64,
  'completedTasks' : IDL.Nat,
  'period' : IDL.Text,
  'pendingTasks' : IDL.Nat,
});
export const ProductivityInsights = IDL.Record({
  'mostActiveProject' : IDL.Opt(ProjectId),
  'longestStreak' : IDL.Nat,
  'mostProductiveDay' : IDL.Opt(Time),
});
export const ProjectStats = IDL.Record({
  'overdueTasks' : IDL.Nat,
  'totalTasks' : IDL.Nat,
  'completionRate' : IDL.Float64,
  'completedTasks' : IDL.Nat,
  'projectId' : ProjectId,
  'overdueRate' : IDL.Float64,
});
export const OverviewData = IDL.Record({
  'totalTasks' : IDL.Nat,
  'yearlyStats' : TimePeriodStats,
  'monthlyStats' : TimePeriodStats,
  'totalProjects' : IDL.Nat,
  'productivityInsights' : ProductivityInsights,
  'weeklyStats' : TimePeriodStats,
  'projectStats' : IDL.Vec(ProjectStats),
});
export const UserPreferences = IDL.Record({
  'defaultView' : IDL.Text,
  'themeMode' : IDL.Text,
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ProjectId], []),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), Time, IDL.Opt(ProjectId), IDL.Text],
      [TaskId],
      [],
    ),
  'deleteProject' : IDL.Func([ProjectId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedTasksHistory' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getOverviewData' : IDL.Func([], [OverviewData], ['query']),
  'getProject' : IDL.Func([ProjectId], [Project], ['query']),
  'getTask' : IDL.Func([TaskId], [Task], ['query']),
  'getTaskContent' : IDL.Func([TaskId], [IDL.Opt(IDL.Text)], ['query']),
  'getTasksByCompletionStatus' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'getTasksByDateRange' : IDL.Func([Time, Time], [IDL.Vec(Task)], ['query']),
  'getTasksByProject' : IDL.Func([ProjectId], [IDL.Vec(Task)], ['query']),
  'getUserPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserPreferences' : IDL.Func([UserPreferences], [], []),
  'toggleTaskCompletion' : IDL.Func([TaskId], [], []),
  'updateTask' : IDL.Func(
      [TaskId, IDL.Text, IDL.Opt(IDL.Text), Time, IDL.Text],
      [],
      [],
    ),
  'updateTaskContent' : IDL.Func([TaskId, IDL.Text], [], []),
  'updateTaskProject' : IDL.Func([TaskId, IDL.Opt(ProjectId)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectId = IDL.Nat;
  const Time = IDL.Int;
  const TaskId = IDL.Nat;
  const Project = IDL.Record({
    'id' : ProjectId,
    'owner' : IDL.Principal,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'color' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Task = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'completionDate' : IDL.Opt(Time),
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'completed' : IDL.Bool,
    'dueDate' : Time,
    'description' : IDL.Opt(IDL.Text),
    'longFormContent' : IDL.Opt(IDL.Text),
    'projectId' : IDL.Opt(ProjectId),
    'priority' : IDL.Text,
  });
  const TimePeriodStats = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completionRate' : IDL.Float64,
    'completedTasks' : IDL.Nat,
    'period' : IDL.Text,
    'pendingTasks' : IDL.Nat,
  });
  const ProductivityInsights = IDL.Record({
    'mostActiveProject' : IDL.Opt(ProjectId),
    'longestStreak' : IDL.Nat,
    'mostProductiveDay' : IDL.Opt(Time),
  });
  const ProjectStats = IDL.Record({
    'overdueTasks' : IDL.Nat,
    'totalTasks' : IDL.Nat,
    'completionRate' : IDL.Float64,
    'completedTasks' : IDL.Nat,
    'projectId' : ProjectId,
    'overdueRate' : IDL.Float64,
  });
  const OverviewData = IDL.Record({
    'totalTasks' : IDL.Nat,
    'yearlyStats' : TimePeriodStats,
    'monthlyStats' : TimePeriodStats,
    'totalProjects' : IDL.Nat,
    'productivityInsights' : ProductivityInsights,
    'weeklyStats' : TimePeriodStats,
    'projectStats' : IDL.Vec(ProjectStats),
  });
  const UserPreferences = IDL.Record({
    'defaultView' : IDL.Text,
    'themeMode' : IDL.Text,
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ProjectId], []),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), Time, IDL.Opt(ProjectId), IDL.Text],
        [TaskId],
        [],
      ),
    'deleteProject' : IDL.Func([ProjectId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedTasksHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getOverviewData' : IDL.Func([], [OverviewData], ['query']),
    'getProject' : IDL.Func([ProjectId], [Project], ['query']),
    'getTask' : IDL.Func([TaskId], [Task], ['query']),
    'getTaskContent' : IDL.Func([TaskId], [IDL.Opt(IDL.Text)], ['query']),
    'getTasksByCompletionStatus' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getTasksByDateRange' : IDL.Func([Time, Time], [IDL.Vec(Task)], ['query']),
    'getTasksByProject' : IDL.Func([ProjectId], [IDL.Vec(Task)], ['query']),
    'getUserPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserPreferences' : IDL.Func([UserPreferences], [], []),
    'toggleTaskCompletion' : IDL.Func([TaskId], [], []),
    'updateTask' : IDL.Func(
        [TaskId, IDL.Text, IDL.Opt(IDL.Text), Time, IDL.Text],
        [],
        [],
      ),
    'updateTaskContent' : IDL.Func([TaskId, IDL.Text], [], []),
    'updateTaskProject' : IDL.Func([TaskId, IDL.Opt(ProjectId)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };