/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface OverviewData {
  'totalTasks' : bigint,
  'yearlyStats' : TimePeriodStats,
  'monthlyStats' : TimePeriodStats,
  'totalProjects' : bigint,
  'productivityInsights' : ProductivityInsights,
  'weeklyStats' : TimePeriodStats,
  'projectStats' : Array<ProjectStats>,
}
export interface ProductivityInsights {
  'mostActiveProject' : [] | [ProjectId],
  'longestStreak' : bigint,
  'mostProductiveDay' : [] | [Time],
}
export interface Project {
  'id' : ProjectId,
  'owner' : Principal,
  'icon' : string,
  'name' : string,
  'createdAt' : Time,
  'color' : string,
}
export type ProjectId = bigint;
export interface ProjectStats {
  'overdueTasks' : bigint,
  'totalTasks' : bigint,
  'completionRate' : number,
  'completedTasks' : bigint,
  'projectId' : ProjectId,
  'overdueRate' : number,
}
export interface Task {
  'id' : TaskId,
  'title' : string,
  'completionDate' : [] | [Time],
  'owner' : Principal,
  'createdAt' : Time,
  'completed' : boolean,
  'dueDate' : Time,
  'description' : [] | [string],
  'longFormContent' : [] | [string],
  'projectId' : ProjectId,
  'priority' : string,
}
export type TaskId = bigint;
export type Time = bigint;
export interface TimePeriodStats {
  'totalTasks' : bigint,
  'completionRate' : number,
  'completedTasks' : bigint,
  'period' : string,
  'pendingTasks' : bigint,
}
export interface UserPreferences {
  'defaultView' : string,
  'themeMode' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[string, string, string], ProjectId>,
  'createTask' : ActorMethod<
    [string, [] | [string], Time, ProjectId, string],
    TaskId
  >,
  'deleteProject' : ActorMethod<[ProjectId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedTasksHistory' : ActorMethod<[string], Array<Task>>,
  'getOverviewData' : ActorMethod<[], OverviewData>,
  'getProject' : ActorMethod<[ProjectId], Project>,
  'getTask' : ActorMethod<[TaskId], Task>,
  'getTaskContent' : ActorMethod<[TaskId], [] | [string]>,
  'getTasksByCompletionStatus' : ActorMethod<[boolean], Array<Task>>,
  'getTasksByDateRange' : ActorMethod<[Time, Time], Array<Task>>,
  'getTasksByProject' : ActorMethod<[ProjectId], Array<Task>>,
  'getUserPreferences' : ActorMethod<[], [] | [UserPreferences]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserPreferences' : ActorMethod<[UserPreferences], undefined>,
  'toggleTaskCompletion' : ActorMethod<[TaskId], undefined>,
  'updateTask' : ActorMethod<
    [TaskId, string, [] | [string], Time, string],
    undefined
  >,
  'updateTaskContent' : ActorMethod<[TaskId, string], undefined>,
  'updateTaskProject' : ActorMethod<[TaskId, ProjectId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];